apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: aasws
        ports:
        - containerPort: 80
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: k8s-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8s-secret
              key: password
        - name: DATABASE
          value: "my_pets"
        imagePullPolicy: Never
---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
